from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class ProviderCatalogEntry:
    provider: str
    name: str
    tier: int
    category: str
    priority: int
    collection_method: str
    implementation_status: str
    labels: tuple[str, ...]
    notes: str

    def to_dict(self) -> dict:
        data = asdict(self)
        data["labels"] = list(self.labels)
        return data


def entry(
    provider: str,
    name: str,
    tier: int,
    category: str,
    priority: int,
    collection_method: str,
    implementation_status: str,
    labels: tuple[str, ...] = (),
    notes: str = "",
) -> ProviderCatalogEntry:
    return ProviderCatalogEntry(
        provider=provider,
        name=name,
        tier=tier,
        category=category,
        priority=priority,
        collection_method=collection_method,
        implementation_status=implementation_status,
        labels=labels,
        notes=notes,
    )


PROVIDER_CATALOG: tuple[ProviderCatalogEntry, ...] = (
    entry("aws", "Amazon Web Services", 0, "hyperscale_cloud", 100, "official_feed", "implemented", ("cloud", "serverless_possible", "cdn_possible")),
    entry("google_cloud", "Google Cloud", 0, "hyperscale_cloud", 100, "official_feed", "implemented", ("cloud", "serverless_possible")),
    entry("azure", "Microsoft Azure", 0, "hyperscale_cloud", 100, "official_feed", "implemented", ("cloud", "service_tags", "serverless_possible")),
    entry("oracle_cloud", "Oracle Cloud OCI", 0, "hyperscale_cloud", 94, "official_feed", "implemented", ("cloud", "serverless_possible")),
    entry("cloudflare", "Cloudflare", 0, "edge_cdn_security", 100, "official_feed", "implemented", ("edge", "cdn", "waf", "workers_possible")),
    entry("fastly", "Fastly", 0, "edge_cdn", 96, "official_feed", "implemented", ("edge", "cdn", "compute_possible")),
    entry("github", "GitHub", 0, "ci_cd_dev_platform", 95, "official_feed", "implemented", ("ci_cd", "webhook", "static_hosting")),
    entry("gitlab", "GitLab.com", 0, "ci_cd_dev_platform", 82, "official_docs", "implemented", ("webhook", "web_api")),
    entry("cloudflare_workers", "Cloudflare Workers", 1, "edge_functions", 100, "official_feed_plus_capability", "covered_by_cloudflare", ("workers_possible", "edge")),
    entry("vercel", "Vercel", 1, "serverless_paas", 96, "docs_scrape_or_capability", "cataloged", ("static_egress_supported", "dynamic_egress")),
    entry("netlify", "Netlify", 1, "serverless_paas", 92, "docs_scrape_or_capability", "cataloged", ("private_connectivity", "dynamic_egress")),
    entry("render", "Render", 1, "paas_app_hosting", 94, "docs_scrape", "planned", ("paas", "outbound_egress")),
    entry("railway", "Railway", 1, "paas_app_hosting", 88, "docs_scrape_or_capability", "planned", ("paas", "static_egress_possible")),
    entry("fly_io", "Fly.io", 1, "edge_app_hosting", 90, "docs_scrape_or_capability", "planned", ("edge_app_hosting", "static_egress_possible")),
    entry("heroku", "Heroku", 1, "paas", 88, "docs_scrape_or_capability", "planned", ("paas", "private_spaces")),
    entry("deno_deploy", "Deno Deploy", 1, "edge_serverless", 84, "capability_only", "cataloged", ("edge_functions",)),
    entry("supabase_edge_functions", "Supabase Edge Functions", 1, "edge_functions", 86, "capability_only", "cataloged", ("unstable_egress",)),
    entry("firebase_functions", "Firebase Functions", 1, "serverless", 84, "via_google_cloud", "covered_by_google_cloud", ("serverless_possible",)),
    entry("firebase_hosting", "Firebase Hosting", 1, "edge_static", 72, "via_google_cloud", "covered_by_google", ("static_hosting",)),
    entry("google_cloud_run", "Google Cloud Run", 1, "serverless_container", 96, "via_google_cloud", "covered_by_google_cloud", ("serverless_possible",)),
    entry("google_cloud_functions", "Google Cloud Functions", 1, "serverless", 94, "via_google_cloud", "covered_by_google_cloud", ("serverless_possible",)),
    entry("google_app_engine", "Google App Engine", 1, "paas", 88, "via_google_cloud", "covered_by_google_cloud", ("paas",)),
    entry("azure_functions", "Azure Functions", 1, "serverless", 94, "via_azure", "covered_by_azure", ("serverless_possible",)),
    entry("azure_app_service", "Azure App Service", 1, "paas", 94, "via_azure", "covered_by_azure", ("paas",)),
    entry("aws_lambda", "AWS Lambda", 1, "serverless", 96, "via_aws", "covered_by_aws", ("serverless_possible",)),
    entry("aws_api_gateway", "AWS API Gateway", 1, "serverless_api", 90, "via_aws", "covered_by_aws", ("serverless_api",)),
    entry("aws_app_runner", "AWS App Runner", 1, "paas", 78, "via_aws", "covered_by_aws", ("paas",)),
    entry("aws_amplify_hosting", "AWS Amplify Hosting", 1, "app_hosting", 72, "via_aws", "covered_by_aws", ("static_hosting",)),
    entry("oracle_functions", "Oracle Functions", 1, "serverless", 72, "via_oracle_cloud", "covered_by_oracle_cloud", ("serverless_possible",)),
    entry("ibm_code_engine", "IBM Code Engine", 1, "serverless_paas", 76, "docs_scrape_or_asn_bgp", "planned", ("serverless_possible",)),
    entry("alibaba_function_compute", "Alibaba Function Compute", 1, "serverless", 78, "docs_scrape_or_asn_bgp", "planned", ("serverless_possible",)),
    entry("tencent_scf", "Tencent SCF", 1, "serverless", 74, "docs_scrape_or_asn_bgp", "planned", ("serverless_possible",)),
    entry("huawei_functiongraph", "Huawei FunctionGraph", 1, "serverless", 72, "asn_bgp_or_capability", "planned", ("serverless_possible",)),
    entry("digitalocean_app_platform", "DigitalOcean App Platform", 1, "paas", 86, "asn_bgp_or_capability", "planned", ("paas",)),
    entry("digitalocean_functions", "DigitalOcean Functions", 1, "serverless", 82, "asn_bgp_or_capability", "planned", ("serverless_possible",)),
    entry("koyeb", "Koyeb", 1, "paas_serverless", 80, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("northflank", "Northflank", 1, "paas", 76, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("platform_sh", "Platform.sh", 1, "paas", 76, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("clever_cloud", "Clever Cloud", 1, "paas", 72, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("scalingo", "Scalingo", 1, "paas", 70, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("qovery", "Qovery", 1, "paas_layer", 60, "capability_only", "cataloged", ("runs_on_customer_cloud",)),
    entry("zeabur", "Zeabur", 1, "paas", 68, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("replit_deployments", "Replit Deployments", 1, "paas_dev_hosting", 74, "asn_bgp_or_capability", "planned", ("paas",)),
    entry("glitch", "Glitch", 1, "app_hosting", 62, "asn_bgp_or_capability", "planned", ("app_hosting",)),
    entry("pythonanywhere", "PythonAnywhere", 1, "paas", 68, "docs_scrape_or_asn_bgp", "planned", ("paas",)),
    entry("val_town", "Val Town", 1, "serverless_dev", 58, "capability_only", "cataloged", ("serverless_dev",)),
    entry("sst_opennext_partners", "SST / OpenNext hosting partners", 1, "framework_layer", 40, "capability_only", "cataloged", ("framework_layer",)),
    entry("akamai", "Akamai", 2, "cdn_security", 96, "docs_scrape_or_customer_specific", "planned", ("cdn", "customer_specific")),
    entry("azure_front_door", "Azure Front Door", 2, "cdn_edge", 94, "via_azure", "covered_by_azure", ("edge", "cdn")),
    entry("azure_cdn", "Azure CDN", 2, "cdn", 88, "via_azure", "covered_by_azure", ("cdn",)),
    entry("google_cloud_cdn", "Google Cloud CDN", 2, "cdn", 86, "via_google_cloud", "covered_by_google_cloud", ("cdn",)),
    entry("bunny_net", "Bunny.net", 2, "cdn_edge", 88, "official_api_or_docs", "planned", ("cdn", "edge")),
    entry("gcore", "Gcore", 2, "cdn_edge_cloud", 90, "official_api_or_docs", "planned", ("cdn", "edge")),
    entry("cdn77", "CDN77", 2, "cdn", 76, "docs_scrape_or_optional", "planned", ("cdn",)),
    entry("imperva", "Imperva", 2, "waf_cdn", 82, "docs_scrape_or_asn_bgp", "planned", ("waf", "cdn")),
    entry("sucuri", "Sucuri", 2, "waf_cdn", 74, "docs_scrape_or_asn_bgp", "planned", ("waf", "cdn")),
    entry("edgio", "Edgio", 2, "cdn_legacy", 50, "asn_bgp", "planned", ("cdn", "legacy")),
    entry("stackpath", "StackPath legacy", 2, "cdn_legacy", 45, "asn_bgp", "planned", ("cdn", "legacy")),
    entry("cachefly", "CacheFly", 2, "cdn", 70, "asn_bgp", "planned", ("cdn",)),
    entry("keycdn", "KeyCDN", 2, "cdn", 68, "docs_scrape_or_asn_bgp", "planned", ("cdn",)),
    entry("quic_cloud", "QUIC.cloud", 2, "cdn_wp_edge", 66, "docs_scrape_or_asn_bgp", "planned", ("cdn",)),
    entry("belugacdn", "BelugaCDN", 2, "cdn", 50, "asn_bgp", "planned", ("cdn",)),
    entry("section_io", "Section.io", 2, "edge_platform", 58, "docs_scrape_or_asn_bgp", "planned", ("edge",)),
    entry("jsdelivr", "jsDelivr", 2, "public_cdn", 50, "capability_only", "cataloged", ("cdn",)),
    entry("netlify_cdn", "Netlify CDN", 2, "cdn_paas", 78, "docs_scrape_or_capability", "cataloged", ("cdn",)),
    entry("vercel_edge_network", "Vercel Edge Network", 2, "edge_paas", 82, "docs_scrape_or_capability", "cataloged", ("edge",)),
    entry("github_actions", "GitHub Actions", 3, "ci_cd", 100, "official_feed", "implemented", ("ci_cd",)),
    entry("github_webhooks", "GitHub Webhooks", 3, "webhook_dev", 96, "official_feed", "implemented", ("webhook",)),
    entry("github_pages", "GitHub Pages", 3, "static_hosting", 82, "official_feed", "implemented", ("static_hosting",)),
    entry("gitlab_web_api", "GitLab.com Web/API", 3, "ci_dev", 86, "official_docs", "implemented", ("webhook", "web_api")),
    entry("gitlab_saas_runners", "GitLab SaaS runners", 3, "ci_cd", 70, "capability_or_asn_bgp", "cataloged", ("ci_cd",)),
    entry("bitbucket_pipelines", "Bitbucket Pipelines", 3, "ci_cd", 80, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("atlassian", "Atlassian Cloud", 3, "webhook_saas", 88, "official_feed", "implemented", ("webhook", "dev_platform")),
    entry("circleci", "CircleCI", 3, "ci_cd", 82, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("buildkite", "Buildkite", 3, "ci_cd", 70, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("travis_ci", "Travis CI", 3, "ci_cd", 66, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("semaphore_ci", "Semaphore CI", 3, "ci_cd", 66, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("appveyor", "AppVeyor", 3, "ci_cd", 60, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("azure_devops_hosted_agents", "Azure DevOps Hosted Agents", 3, "ci_cd", 90, "via_azure", "covered_by_azure", ("ci_cd",)),
    entry("aws_codebuild", "AWS CodeBuild", 3, "ci_cd", 78, "via_aws", "covered_by_aws", ("ci_cd",)),
    entry("google_cloud_build", "Google Cloud Build", 3, "ci_cd", 78, "via_google_cloud", "covered_by_google_cloud", ("ci_cd",)),
    entry("codefresh", "Codefresh", 3, "ci_cd", 58, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("harness_cloud", "Harness Cloud", 3, "ci_cd", 62, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("teamcity_cloud", "TeamCity Cloud", 3, "ci_cd", 58, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("buddy", "Buddy", 3, "ci_cd", 54, "docs_scrape_or_asn_bgp", "planned", ("ci_cd",)),
    entry("drone_cloud", "Drone Cloud", 3, "ci_cd", 45, "asn_bgp_or_capability", "planned", ("ci_cd",)),
    entry("ibm_cloud", "IBM Cloud", 4, "regional_cloud", 86, "docs_scrape_or_asn_bgp", "planned", ("cloud",)),
    entry("alibaba_cloud", "Alibaba Cloud", 4, "regional_cloud", 88, "docs_scrape_or_asn_bgp", "planned", ("cloud",)),
    entry("tencent_cloud", "Tencent Cloud", 4, "regional_cloud", 84, "docs_scrape_or_asn_bgp", "planned", ("cloud",)),
    entry("huawei_cloud", "Huawei Cloud", 4, "regional_cloud", 80, "asn_bgp", "planned", ("cloud",)),
    entry("baidu_ai_cloud", "Baidu AI Cloud", 4, "regional_cloud", 68, "asn_bgp", "planned", ("cloud",)),
    entry("kingsoft_cloud", "Kingsoft Cloud", 4, "regional_cloud", 62, "asn_bgp", "planned", ("cloud",)),
    entry("ucloud", "UCloud", 4, "regional_cloud", 62, "asn_bgp", "planned", ("cloud",)),
    entry("jd_cloud", "JD Cloud", 4, "regional_cloud", 58, "asn_bgp", "planned", ("cloud",)),
    entry("naver_cloud", "Naver Cloud", 4, "regional_cloud", 72, "asn_bgp", "planned", ("cloud",)),
    entry("kakao_cloud", "Kakao Cloud", 4, "regional_cloud", 60, "asn_bgp", "planned", ("cloud",)),
    entry("nhn_cloud", "NHN Cloud", 4, "regional_cloud", 58, "asn_bgp", "planned", ("cloud",)),
    entry("sakura_cloud", "Sakura Cloud", 4, "regional_cloud", 70, "asn_bgp", "planned", ("cloud",)),
    entry("ovhcloud", "OVHcloud", 4, "regional_cloud", 92, "asn_bgp", "planned", ("cloud_vps",)),
    entry("hetzner", "Hetzner Cloud", 4, "regional_cloud", 94, "asn_bgp", "planned", ("cloud_vps", "hosting")),
    entry("scaleway", "Scaleway", 4, "regional_cloud", 88, "asn_bgp", "planned", ("cloud_vps",)),
    entry("ionos", "IONOS Cloud", 4, "regional_cloud", 86, "asn_bgp", "planned", ("cloud_vps",)),
    entry("open_telekom_cloud", "Open Telekom Cloud", 4, "regional_cloud", 78, "asn_bgp", "planned", ("cloud",)),
    entry("stackit", "STACKIT", 4, "regional_cloud", 76, "asn_bgp", "planned", ("cloud",)),
    entry("exoscale", "Exoscale", 4, "regional_cloud", 78, "asn_bgp", "planned", ("cloud_vps",)),
    entry("infomaniak", "Infomaniak Public Cloud", 4, "regional_cloud", 70, "asn_bgp", "planned", ("cloud",)),
    entry("yandex_cloud", "Yandex Cloud", 4, "regional_cloud", 78, "asn_bgp_or_docs", "planned", ("cloud",)),
    entry("vk_cloud", "VK Cloud", 4, "regional_cloud", 72, "asn_bgp_or_docs", "planned", ("cloud",)),
    entry("selectel", "Selectel", 4, "regional_cloud", 76, "asn_bgp_or_docs", "planned", ("cloud_vps",)),
    entry("timeweb_cloud", "Timeweb Cloud", 4, "regional_cloud", 64, "asn_bgp", "planned", ("cloud_vps",)),
    entry("cloud_ru", "Cloud.ru", 4, "regional_cloud", 62, "asn_bgp", "planned", ("cloud",)),
    entry("mts_cloud", "MTS Cloud", 4, "regional_cloud", 60, "asn_bgp", "planned", ("cloud",)),
    entry("beeline_cloud", "Beeline Cloud", 4, "regional_cloud", 56, "asn_bgp", "planned", ("cloud",)),
    entry("rostelecom_cloud", "Rostelecom Cloud", 4, "regional_cloud", 56, "asn_bgp", "planned", ("cloud",)),
    entry("arvancloud", "ArvanCloud", 4, "regional_cloud_cdn", 58, "asn_bgp", "planned", ("cloud", "cdn")),
    entry("stc_cloud", "STC Cloud", 4, "regional_cloud", 54, "asn_bgp", "planned", ("cloud",)),
    entry("etisalat_cloud", "Etisalat Cloud", 4, "regional_cloud", 52, "asn_bgp", "planned", ("cloud",)),
    entry("turkcell_cloud", "Turkcell Cloud", 4, "regional_cloud", 52, "asn_bgp", "planned", ("cloud",)),
    entry("locaweb", "Locaweb", 4, "regional_cloud_hosting", 52, "asn_bgp", "planned", ("cloud", "hosting")),
    entry("uol_host", "UOL Host", 4, "regional_cloud_hosting", 50, "asn_bgp", "planned", ("cloud", "hosting")),
    entry("kinghost", "KingHost", 4, "regional_cloud_hosting", 48, "asn_bgp", "planned", ("hosting",)),
    entry("macquarie_cloud", "Macquarie Cloud", 4, "regional_cloud", 50, "asn_bgp", "planned", ("cloud",)),
    entry("catalyst_cloud", "Catalyst Cloud", 4, "regional_cloud", 50, "asn_bgp", "planned", ("cloud",)),
    entry("safaricom_cloud", "Safaricom Cloud", 4, "regional_cloud", 44, "asn_bgp", "planned", ("cloud",)),
    entry("upcloud", "UpCloud", 4, "regional_cloud", 86, "asn_bgp", "planned", ("cloud_vps",)),
    entry("leaseweb", "Leaseweb Cloud", 4, "regional_cloud", 86, "asn_bgp", "planned", ("cloud_vps", "hosting")),
    entry("digitalocean", "DigitalOcean", 5, "cloud_vps", 98, "asn_bgp", "planned", ("cloud_vps", "paas_possible")),
    entry("linode", "Akamai Connected Cloud / Linode", 5, "cloud_vps", 96, "asn_bgp", "planned", ("cloud_vps",)),
    entry("vultr", "Vultr / Choopa", 5, "cloud_vps", 96, "asn_bgp", "planned", ("cloud_vps",)),
    entry("contabo", "Contabo", 5, "hosting_vps", 92, "asn_bgp", "planned", ("hosting",)),
    entry("netcup", "netcup", 5, "hosting_vps", 86, "asn_bgp", "planned", ("hosting",)),
    entry("strato", "Strato", 5, "hosting_vps", 78, "asn_bgp", "planned", ("hosting",)),
    entry("hostinger", "Hostinger", 5, "hosting_vps", 76, "asn_bgp", "planned", ("hosting",)),
    entry("namecheap", "Namecheap Hosting", 5, "hosting_vps", 70, "asn_bgp", "planned", ("hosting",)),
    entry("godaddy", "GoDaddy Hosting", 5, "hosting_vps", 70, "asn_bgp", "planned", ("hosting",)),
    entry("rackspace", "Rackspace", 5, "hosting_vps", 84, "asn_bgp", "planned", ("hosting",)),
    entry("hostdime", "HostDime", 5, "hosting_vps", 76, "asn_bgp", "planned", ("hosting",)),
    entry("liquid_web", "Liquid Web", 5, "hosting_vps", 78, "asn_bgp", "planned", ("hosting",)),
    entry("hivelocity", "Hivelocity", 5, "hosting_vps", 78, "asn_bgp", "planned", ("hosting",)),
    entry("phoenixnap", "PhoenixNAP", 5, "hosting_vps", 76, "asn_bgp", "planned", ("hosting",)),
    entry("clouvider", "Clouvider", 5, "hosting_vps", 70, "asn_bgp", "planned", ("hosting",)),
    entry("m247", "M247", 5, "hosting_vps", 70, "asn_bgp", "planned", ("hosting",)),
    entry("nforce", "NForce", 5, "hosting_vps", 66, "asn_bgp", "planned", ("hosting",)),
    entry("worldstream", "Worldstream", 5, "hosting_vps", 66, "asn_bgp", "planned", ("hosting",)),
    entry("serverius", "Serverius", 5, "hosting_vps", 64, "asn_bgp", "planned", ("hosting",)),
    entry("voxility", "Voxility", 5, "hosting_vps", 64, "asn_bgp", "planned", ("hosting",)),
    entry("aruba_cloud", "Aruba Cloud", 5, "hosting_vps", 62, "asn_bgp", "planned", ("hosting",)),
    entry("seeweb", "Seeweb", 5, "hosting_vps", 60, "asn_bgp", "planned", ("hosting",)),
    entry("transip", "TransIP", 5, "hosting_vps", 60, "asn_bgp", "planned", ("hosting",)),
    entry("host_europe", "Host Europe", 5, "hosting_vps", 58, "asn_bgp", "planned", ("hosting",)),
    entry("equinix_metal", "Equinix Metal", 5, "bare_metal_datacenter", 84, "asn_bgp", "planned", ("bare_metal",)),
    entry("quota_guard", "QuotaGuard", 6, "managed_egress", 90, "docs_scrape_or_asn_bgp", "planned", ("managed_egress",)),
    entry("fixie", "Fixie", 6, "managed_egress", 82, "docs_scrape_or_asn_bgp", "planned", ("managed_egress",)),
    entry("proximo", "Proximo", 6, "managed_egress", 76, "docs_scrape_or_asn_bgp", "planned", ("managed_egress",)),
    entry("cloudflare_dedicated_egress", "Cloudflare Dedicated Egress IPs", 6, "managed_egress", 72, "customer_specific_capability", "cataloged", ("customer_specific",)),
    entry("ngrok", "ngrok", 6, "dev_tunnel_edge", 72, "docs_scrape_or_asn_bgp", "planned", ("tunnel", "edge")),
    entry("stripe", "Stripe Webhooks/API", 7, "webhook_automation", 92, "official_feed", "implemented", ("webhook", "payments")),
    entry("shopify_webhooks", "Shopify Webhooks", 7, "webhook_automation", 80, "docs_scrape_or_asn_bgp", "planned", ("webhook", "ecommerce")),
    entry("twilio_webhooks", "Twilio Webhooks", 7, "webhook_automation", 76, "docs_scrape_or_asn_bgp", "planned", ("webhook", "comms")),
    entry("sendgrid", "SendGrid", 7, "webhook_automation", 74, "docs_scrape_or_asn_bgp", "planned", ("email", "webhook")),
    entry("mailgun", "Mailgun", 7, "webhook_automation", 72, "docs_scrape_or_asn_bgp", "planned", ("email", "webhook")),
    entry("postmark", "Postmark", 7, "webhook_automation", 68, "docs_scrape_or_asn_bgp", "planned", ("email", "webhook")),
    entry("zapier", "Zapier", 7, "webhook_automation", 76, "docs_scrape_or_asn_bgp", "planned", ("automation",)),
    entry("make", "Make.com", 7, "webhook_automation", 70, "docs_scrape_or_asn_bgp", "planned", ("automation",)),
    entry("datadog_synthetics", "Datadog Synthetic", 7, "monitoring_sources", 72, "docs_scrape_or_asn_bgp", "planned", ("monitoring",)),
    entry("pingdom", "Pingdom", 7, "monitoring_sources", 70, "docs_scrape_or_asn_bgp", "planned", ("monitoring",)),
    entry("uptimerobot", "UptimeRobot", 7, "monitoring_sources", 70, "docs_scrape_or_asn_bgp", "planned", ("monitoring",)),
    entry("better_stack", "Better Stack", 7, "monitoring_sources", 64, "docs_scrape_or_asn_bgp", "planned", ("monitoring",)),
    entry("statuscake", "StatusCake", 7, "monitoring_sources", 58, "docs_scrape_or_asn_bgp", "planned", ("monitoring",)),
    entry("shodan", "Shodan", 8, "internet_scanner", 90, "docs_scrape_or_asn_bgp", "planned", ("known_scanner",)),
    entry("censys", "Censys", 8, "internet_scanner", 90, "docs_scrape_or_asn_bgp", "planned", ("known_scanner",)),
    entry("shadowserver", "Shadowserver", 8, "internet_measurement", 88, "docs_scrape_or_asn_bgp", "planned", ("measurement",)),
    entry("rapid7_sonar", "Rapid7 Sonar", 8, "internet_measurement", 82, "docs_scrape_or_asn_bgp", "planned", ("measurement",)),
    entry("binaryedge", "BinaryEdge", 8, "internet_scanner", 76, "docs_scrape_or_asn_bgp", "planned", ("known_scanner",)),
    entry("zoomeye", "ZoomEye", 8, "internet_scanner", 70, "docs_scrape_or_asn_bgp", "planned", ("known_scanner",)),
    entry("greynoise", "GreyNoise", 8, "internet_intel", 70, "optional_api", "cataloged", ("intel",)),
    entry("leakix", "LeakIX", 8, "internet_scanner", 70, "docs_scrape_or_asn_bgp", "planned", ("known_scanner",)),
)


def provider_catalog() -> list[dict]:
    return [item.to_dict() for item in PROVIDER_CATALOG]
